### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jackson-jackson** [FellowTraveler/otapij#24]
System details: iMac i5 running Ubuntu 12.04

What happened:

I "withdrew cash" from a dDVC account labeled "Stretch-dDEVCOIN" which then automatically created an account called "DigiDVC" where the cash was deposited in to. I then deposited the cash back into "Stretch-dDEVCOIN" and tried to delete the now empty "DigiDVC" account from the Account List. When the pop up asked me if I was sure I wanted to delete the account I clicked "continue" and it instantly crashed. It now crashes every time I try to delete that empty "DigiDVC" account.

**Comment by FellowTraveler** [comment]
On 10/12/12 10:50 PM, Jackson Warren wrote:

> System details: iMac i5 running Ubuntu 12.04
> 
> What happened:
> 
> I "withdrew cash" from a dDVC account labeled "Stretch-dDEVCOIN" which
> then automatically created an account called "DigiDVC" where the cash
> was deposited in to. I then deposited the cash back into
> "Stretch-dDEVCOIN" and tried to delete the now empty "DigiDVC" account
> from the Account List. When the pop up asked me if I was sure I wanted
> to delete the account I clicked "continue" and it instantly crashed. It
> now crashes every time I try to delete that empty "DigiDVC" account.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FellowTraveler/Moneychanger/issues/24.

What's the output?

Gimme the last screenful.

-FT

**Comment by jackson-jackson** [comment]
values.size():6
accountTable.getColumn(2)2
In clearPanel cash top
valueChanged Action Listener :4e:javax.swing.DefaultListSelectionModel 280807668 ={4}
Type:CashPurseAccount
In cash purse table mode---set values size:0
cash purse getColumn() count:7
userSelection:0
ot_terminate: ot_terminate caught unknown/unhandled exception.
[bt]: (1) /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : +0xb5846 [0x7fd4d2e26846]
[bt]: (2) /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : +0xb5873 [0x7fd4d2e26873]
[bt]: (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : +0xb596e [0x7fd4d2e2696e]
[bt]: (4) /home/jackson/.local/lib/libot.so.0 : BigUnsignedInABase::BigUnsignedInABase(std::string const&, unsigned short)+0x1a5 [0x7fd459478805]
[bt]: (5) /home/jackson/.local/lib/libot.so.0 : stringToBigUnsignedBase62(std::string const&)+0x15 [0x7fd4594770e5]
[bt]: (6) /home/jackson/.local/lib/libot.so.0 : stringToBigIntegerBase62(std::string const&)+0x2c [0x7fd45947751c]
[bt]: (7) /home/jackson/.local/lib/libot.so.0 : OTIdentifier::SetString(OTString const&)+0x4f [0x7fd459289dff]
[bt]: (8) /home/jackson/.local/lib/libot.so.0 : OTIdentifier::SetString(char const_)+0x2f [0x7fd459289f6f]
[bt]: (9) /home/jackson/.local/lib/libot.so.0 : OTIdentifier::OTIdentifier(char const_)+0x37 [0x7fd459289ff7]
[bt]: (10) /home/jackson/.local/lib/libotapi.so.0 : OT_API_Wallet_CanRemoveAccount(char const*)+0x40 [0x7fd4597e4e40]
[bt]: (11) /home/jackson/.local/lib/libotapi-java.so.0.0.0 : Java_com_wrapper_core_jni_otapiJNI_OT_1API_1Wallet_1CanRemoveAccount+0x43 [0x7fd45a27af23]
[bt]: (12) [0x7fd4c9010d68]

Aborted (core dumped)
jackson@jackson-iMac:~$

**Comment by FellowTraveler** [comment]
"If you try to delete a cash purse in Moneychanger, the way you would normally delete a real account, then Moneychanger crashes. Fix: grey-out the delete button when cash purses are selected on the main tab."
