### ISSUE TITLE
Minor : Nym cannot be deleted

### ISSUE THREAD

**Issue by NYCBrit** [FellowTraveler/otapij#5]
When I click on the - sign on the Nyms page, it tells me the Nym cannot be deleted. I can't see a reason why it can't be deleted. I can rename it without issue.

**Comment by FellowTraveler** [comment]
The reason it wouldn't allow you to delete a Nym (normally), is if there are any accounts / purses etc that are USING that Nym.

However, the current implementation of "CanDeleteNym?" might just have a "return false" in it, with no other code. I'll have to take a look at it and fix that.  (I'm about to fix up a few other methods for the market code, so I'll check this at the same time.)

**Comment by FellowTraveler** [comment]
This should be fixed now.  There are API calls for deleting accounts and nyms from the server as well as from the wallet. The calls don't always succeed (they have requirements, for example you cannot delete a Nym who still has accounts, and you cannot delete an account that still has a balance. Etc.) There are also calls for checking to see IF you can delete.
